config/routes.rb
BreeasyContact::Application.routes.draw do

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"

  resources :users do
    resources :affiliates
  end
  
  resources :sessions
  resources :contacts
  
  namespace :api do
      namespace :v1 do
        resources :users, :apps
      end
    end
 resources :breeasy_affiliates, :only => [:show, :new, :create, :edit, :update] 
  
  match 'thank_you/:id' => 'contacts#thank_you', :as => 'thank_you'
  match 'new_affiliate_details' => 'users#new_affiliate_details', :as => :new_affiliate_details
  match 'users/create_affiliate_details' => 'users#create_affiliate_details', :as => :create_affiliate_details
  match 'affiliate-home' => 'affiliates#home', :as => :affiliate_home
  match 'affiliate-tips' => 'affiliates#tips', :as => :affiliate_tips
  match 'affiliate-help' => 'affiliates#help', :as => :affiliate_help
  match 'affiliate-page' => 'affiliates#page', :as => :affiliate_page
  match 'affiliate-financials' => 'affiliates#financials', :as => :affiliate_financials
  match 'master-affiliate-signup' =>'affiliates#new_master', :as => :new_master
  match 'standard-affiliate-signup' => 'affiliates#new_standard', :as => :new_standard
  match 'master-affiliate-earnings-calculator' => 'affiliates#affiliate_calculator', :as => :master_affiliate_earnings
  match 'calculate-commissions' => 'affiliates#calculate_commissions', :as => :calculate_commissions
  match 'standard-affiliate-earnings-calculator' => 'affiliates#standard_affiliate_calculator', :as => :standard_affiliate_earnings
  match 'standard-calculate-commissions' => 'affiliates#standard_calculate_commissions', :as => :standard_calculate_commissions
  match 'sub-affiliate/:master_id' => 'affiliates#sub_affiliate', :as => :sub_affiliate
  match 'api/v1/user/login' => 'api/v1/users#login'
  match 'users/create_contact' => 'users#create_contact'
  match 'breeasy-affiliate-program/:affiliate_id' => "affiliates#breeasy_affiliate_program", :as => :breeasy_affiliate_program
  match 'breeasy-affiliate-sample-page' => "breeasy_affiliates#sample", :as => :breeasy_affiliate_page_sample
  match 'breeasy-affiliate-preview-page' => "breeasy_affiliates#preview", :as => :breeasy_affiliate_preview
  root :to => 'affiliates#home'
  
  

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation, :master, :master_id, :account_executive_id
  
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
  has_one :affiliate_detail, :dependent => :destroy
  has_many :urls, :dependent => :destroy
  has_many :sub_affiliates, :class_name => "User", :foreign_key => "master_id"
  belongs_to :master_affiliate, :class_name => "User", :foreign_key => "master_id"
  belongs_to :account_executive
  has_one :content
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
 
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
  def get_breeasy_billing_referrals
    ref_code = self.affiliate_detail.affiliate_code
    response = HTTParty.get("http://billing.breeasy.com/api/v1/user/referral_users.json?referrer=#{ref_code}")
    return response
  end
  
  def get_bfsb_referrals
    ref_code = self.affiliate_detail.affiliate_code
    response = HTTParty.get("http://app.breeasy.com/api/v1/users.json?referrer=#{ref_code}")
    return response
  end
  def get_breeasy_account
    retval = false
  ref_code = self.affiliate_detail.affiliate_code
  response = HTTParty.get("http://app.breeasy.com/api/v1/user/master_affiliate.json?affiliate_code=#{ref_code}")
  unless response['user'].nil?
    if response['user']['master_affiliate_id'] == ref_code
      retval = true
    end
  end
  return retval
  end
  
  def breeasy_username
    ref_code = self.affiliate_detail.affiliate_code
    response = HTTParty.get("http://app.breeasy.com/api/v1/user/master_affiliate.json?affiliate_code=#{ref_code}")
    unless response['user'].nil?
      retval = response['user']['username']
    end
    return retval
  end
end

app/controllers/api/v1/users_controller.rb
module Api
  module V1
    class UsersController < ApplicationController
      skip_before_filter :current_user, :only => [:create, :login, :show]
      # class Task < ::Task
      #   # def as_json(options = {})
      #   #   super.merge(released_on: released_at.to_date)
      #   # end
      # end
      #cred = YAML.load_file("#{Rails.root}/config/auth.yml")
      #raise cred.inspect
      
     # http_basic_authenticate_with name: "breeasy_user", password: "rt8932n12340982fj"
      #http_basic_authenticate_with name: cred['auth']['name'], password: cred['auth']['password']
      respond_to :json
      # 
      def show
        user = User.find(params[:id])
          
        respond_with user.affiliate_detail
      end
      # 
      # def create
      #  # respond_with User.create(params[:user])
      #  user = User.new(params[:user])
      #  user.source = "InstaInvoice"
      #  if user.save
      #    UserMailer.welcome_user(user).deliver
      #  end
      #  respond_with user
      #   
      # end
      # 
      # def update
      #   respond_with User.update(params[:id], params[:user])
      # end
      # 
      # def destroy 
      #   respond_with User.destroy(params[:id])
      # end
      
      def create
        respond_with  user = User.create(params[:user])
      end
      
      def login
        user = User.authenticate(params[:email], params[:password])
      
          respond_with user


      end
      # def update_user_details
      #   user = User.find(params[:id])
      #   user.user_detail.update_attributes(params[:user_detail])
      #   respond_with user.user_detail
      # 
      # end
      # def create_user_details
      #   detail = UserDetail.create(params[:user_detail])
      #     respond_with detail
      # end
      # def referral_users
      #   users = User.find_all_by_referrer(params[:referrer])
      #   respond_with users
      # end
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_filter :logged_in, :except => [:new, :create, :create_contact]
  
  def new
      @user = User.new
      @referrer = "breeasy"
  end
  
  def show
  end

    def create
      @user = User.new(params[:user])
      if @user.save
        session[:user_id] = @user.id
        if @user.master
          AffiliateMailer.welcome_master(@user).deliver
        elsif @user.master_id
          AffiliateMailer.welcome_sub_standard(@user).deliver
        else
          AffiliateMailer.welcome_standard(@user).deliver
        end
        redirect_to new_affiliate_details_path, :notice => "Signed up!"
      else
        if @user.master
          render "affiliates/new_master"
        elsif @user.master_id
          @master_affiliate = User.find(@user.master_id)
          render 'affiliates/sub_affiliate'
        else
          render "affiliates/new_standard"
        end
      end
    end
    
    
    
    def new_affiliate_details
      @affiliate_detail = AffiliateDetail.new
    end
    
    def create_affiliate_details
      @affiliate_detail = AffiliateDetail.new(params[:affiliate_detail])
      #raise @affiliate_detail.inspect
      if @affiliate_detail.save
        
        #create affiliate_urls
        code = @affiliate_detail.affiliate_code
        #url_path = "http://app.breeasy.com/signup?referrer=#{code}"
        #link = "<a href='#{url_path}'>Edit This Text</a>"
        user = @affiliate_detail.user
        Program.all.each do |p|
          url_path = p.url_path + code
          link = "<a href='#{url_path}'>Edit This Text</a>"
          url = user.urls.build(:program_description => p.name, :url => url_path, :link => link, :program_id => p.id)
          url.save
        end
        redirect_to user_affiliates_path(current_user.id)
      else
        render 'new_affiliate_details'
      end
      
    end
    def create_contact
        @ml = ContactList.new(params[:mail_list])
        #raise @ml.inspect
          respond_to do |format|
             if @ml.save
               format.json { render json: @ml }
             else
               format.json { render json: @ml.errors }
             end
           end
     end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_master_terms.html.erb
<h2>Breeasy Master Affiliate Terms</h2>
All Pricing is set by Breeasy.com.  Breeasy will, from time to time, run specials, promos, etc. as well as offer discounts as an incentive.  Commissions paid are on these discounted prices, when
applicable.<br>
Payments made every 15th of the month with a minimum of $10.00.<br>
Affiliates are expected to maintain a commission earnings of $100.00 per month, after 3 months of joining the program.  Affiliates that perform below this minimum
may be cancelled from the program with 30 days notice at the discretion of Breeasy.com management.<br>
For each new paid annual subscription, each master affiliate can earn up to 50% commission and up to 40% commission on annual renewals and monthly subscriptions.  Commission rates vary by plan. Commissions are earned and are payable to the affiliate when the 
subscription is paid by the subscriber.  In the case that a subscription is cancelled, any commissions previously paid on new or renewal and annual subscriptions
are pro-rated and credited against future payments.<br>
Master Affiliates earn 15% of all sub-affiliates, and there is no limit to the number of sub-affiliates a Master affiliate can have.  Sub-affiliates agree to the same terms as Breeasy Standard Affiliates.  The Standard Affiliate terms are shown for your reference.<br>
The Breeasy Master Affiliate costs USD $995.00 per year.  An Invoice will be sent to the email address associated with the Affiliate User.  At times, Breeasy may offer promotions on the Breeasy Master Affiliate annual membership fee.
<br>
To reduce fraud, affiliates that have a subscriber cancellation rate higher than 10% will result in cancellation of the affiliate program and commission payments will be suspended.<br>
In certain cases, refunds for cancelled subscriptions will be pro-rated and the any commission paid will be deducted from any refund amount.<br>
Commissions rates are subject to change and can be viewed on your dashboard.  Your dashboard is available once you complete your user details.<br>

app/views/users/_terms.html.erb
	<h2>Breeasy Affiliate Terms</h2>
	All Pricing is set by Breeasy.com.  Breeasy will, from time to time, run specials, promos, etc. as well as offer discounts as an incentive.  Commissions paid are on these discounted prices, when
	applicable.<br>
	Payments made every 15th of the month with a minimum of $10.00.<br>
	Affiliates are expected to maintain a commission earnings of $100.00 per month, after 3 months of joining the program.  Affiliates that perform below this minimum
	may be cancelled from the program with 30 days notice at the discretion of Breeasy.com management.<br>
	For each new paid annual and monthly subscription, each affiliate earn up to 35%.  Renewals earn commission rates up to 25% Renewals are annual or monthly.  Commission rates vary by plan. Commissions are earned and are payable to the affiliate when the 
		subscription is paid by the subscriber.  In the case that a subscription is cancelled, any commissions previously paid on new or renewal and annual subscriptions
		 are pro-rated and credited against future payments.<br>

	To reduce fraud, affiliates that have a subscriber cancellation rate higher than 10% will result in cancellation of the affiliate program and commission payments will be suspended.<br>
	In certain cases, refunds for cancelled subscriptions will be pro-rated and the any commission paid will be deducted from any refund amount.<br>
	Commissions rates are subject to change and can be viewed on your dashboard.  Your dashboard is available once you complete your user details.<br>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>

app/views/users/new_affiliate_details.html.erb
<h1>Add Your User Details</h1>
<div id="bd">
	<div class="yui-g">
			Email Address:  <%= current_user.email %> - Please be complete as possible.
			<%= simple_form_for @affiliate_detail, :url => create_affiliate_details_path do |f| %>
			<%= f.error_notification %>
 			<%= f.input  :user_id, :as => :hidden, :input_html => {:value => current_user.id} %>
			<%= f.input :first_name %>
			<%= f.input :last_name %>
			<%= f.input :title %>
			<%= f.input :company %>
			<%= f.input :website %>
			<%= f.input :phone %>
			<%= f.input :address %>
			<%= f.input :city %>
			<%= f.input :state %>
			<%= f.input :post_code %>
			<%= f.input :country, :as => :string %>
			<%= f.input :affiliate_code, :hint => "Create your own affiliate code - no special characters or spaces", :placeholder => "e.g. Your Company Name" %>
			<% if current_user.master %>
				<%= render :partial => "users/master_terms" %>
				<%= render :partial => 'users/terms' %>
			<% else %>
				<%= render :partial => "users/terms" %>
			<% end %>
			<br>
			<% if current_user.master %>
				<%= f.input :accepted_terms, :label => "  I have read, understand, and accept the Terms of the Breeasy Master Affiliate Program." %>
			<% else %>
				<%= f.input :accepted_terms, :label => "  I have read, understand, and accept the Terms of the Breeasy Affiliate Program." %>
			<% end %>

			<%= f.submit "Create Affiliate Account" %>
			<% end %>

	</div>
</div>