config/routes.rb
BreeasyContact::Application.routes.draw do

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"

  resources :users do
    resources :affiliates
  end
  
  resources :sessions
  resources :contacts
  
  namespace :api do
      namespace :v1 do
        resources :users, :apps
      end
    end
 resources :breeasy_affiliates, :only => [:show, :new, :create, :edit, :update] 
  
  match 'thank_you/:id' => 'contacts#thank_you', :as => 'thank_you'
  match 'new_affiliate_details' => 'users#new_affiliate_details', :as => :new_affiliate_details
  match 'users/create_affiliate_details' => 'users#create_affiliate_details', :as => :create_affiliate_details
  match 'affiliate-home' => 'affiliates#home', :as => :affiliate_home
  match 'affiliate-tips' => 'affiliates#tips', :as => :affiliate_tips
  match 'affiliate-help' => 'affiliates#help', :as => :affiliate_help
  match 'affiliate-page' => 'affiliates#page', :as => :affiliate_page
  match 'affiliate-financials' => 'affiliates#financials', :as => :affiliate_financials
  match 'master-affiliate-signup' =>'affiliates#new_master', :as => :new_master
  match 'standard-affiliate-signup' => 'affiliates#new_standard', :as => :new_standard
  match 'master-affiliate-earnings-calculator' => 'affiliates#affiliate_calculator', :as => :master_affiliate_earnings
  match 'calculate-commissions' => 'affiliates#calculate_commissions', :as => :calculate_commissions
  match 'standard-affiliate-earnings-calculator' => 'affiliates#standard_affiliate_calculator', :as => :standard_affiliate_earnings
  match 'standard-calculate-commissions' => 'affiliates#standard_calculate_commissions', :as => :standard_calculate_commissions
  match 'sub-affiliate/:master_id' => 'affiliates#sub_affiliate', :as => :sub_affiliate
  match 'api/v1/user/login' => 'api/v1/users#login'
  match 'users/create_contact' => 'users#create_contact'
  match 'breeasy-affiliate-program/:affiliate_id' => "affiliates#breeasy_affiliate_program", :as => :breeasy_affiliate_program
  match 'breeasy-affiliate-sample-page' => "breeasy_affiliates#sample", :as => :breeasy_affiliate_page_sample
  match 'breeasy-affiliate-preview-page' => "breeasy_affiliates#preview", :as => :breeasy_affiliate_preview
  root :to => 'affiliates#home'
  
  

end

app/controllers/affiliates_controller.rb
class AffiliatesController < ApplicationController
  layout 'members', :only => [:index, :edit, :tips, :help]
  #layout 'breeasy_affiliate_program', :only => [:breeasy_affiliate_program]
  before_filter :logged_in, :except => [:home, :new_standard, :new_master, :affiliate_calculator, :calculate_commissions, :sub_affiliate,
    :standard_calculate_commissions, :standard_affiliate_calculator, :breeasy_affiliate_program]
  
  
   def get_owner
     @user = User.find(params[:user_id])
   end
  
  
  def new_standard
    @user = User.new
  end
  def new_master
    @user = User.new
  end
  
  def edit
    @affiliate_detail = AffiliateDetail.find(params[:id])
  end

  def index
    #need a method that returns all the users that have this users affiliate code in BFSB
  # code = current_user.affiliate_detail.affiliate_code
   #go to BFB and get all the users that have this code.
   
  # @bfb_users = some_url_at_bfb(code)
  
   #with each user, need to know the account status; i.e. if they paid etc.    
  end
  
  
  def show
  end
  
  def update
    @affiliate_detail = AffiliateDetail.find(params[:id])
    if @affiliate_detail.update_attributes(params[:affiliate_detail])
      redirect_to user_affiliates_path(current_user.id)
    else
      render 'edit'
    end
    
  end
  def calculate_commissions
    #get direct earnings for master calculator
    comm_5 = 9.95 * params[:direct_5].to_f * 0.40 * 12
    comm_6 = 14.95 * params[:direct_6].to_f * 0.40 * 12
    comm_7 = 99.95 * params[:direct_7].to_f * 0.50
    comm_8 = 149.95 * params[:direct_8].to_f * 0.50
    @total_count = params[:direct_5].to_f + params[:direct_6].to_f + params[:direct_7].to_f + params[:direct_8].to_f
    @total_direct = comm_5 + comm_6 + comm_7 + comm_8
    plans = []
    sub_count = params[:number_of_subs].to_f

    sub_5 = 9.95 * params[:sub_5].to_f * 0.15 * sub_count * 12
    sub_6 = 14.95 * params[:sub_6].to_f * 0.15 * sub_count * 12
    sub_7 = 99.95 * params[:sub_7].to_f * 0.15 * sub_count
    sub_8 = 149.95 * params[:sub_8].to_f * 0.15 * sub_count
    @total_sub = sub_5 + sub_6 + sub_7 + sub_8
    
    redirect_to master_affiliate_earnings_path(:direct => @total_direct, :sub_affiliate => @total_sub, :total_count => @total_count, :sub_count => sub_count)
  end
  
  
  def affiliate_calculator
    @total_direct = params[:direct] unless params[:direct].nil?
    @total_sub = params[:sub_affiliate] unless params[:sub_affiliate].nil?
    @total = @total_sub.to_f + @total_direct.to_f
    @total_count = params[:total_count].to_f
    @sub_count = params[:sub_count].to_f
    
  end
  def sub_affiliate
  @master_affiliate = User.find params[:master_id]
  @user = User.new
    
  end
  def standard_calculate_commissions
    #get direct earnings for master calculator
    comm_5 = 9.95 * params[:direct_1].to_f * 0.25 * 12
    comm_6 = 14.95 * params[:direct_2].to_f * 0.25 * 12
    comm_7 = 99.95 * params[:direct_3].to_f * 0.35
    comm_8 = 149.95 * params[:direct_4].to_f * 0.35
    @total_count = params[:direct_1].to_f + params[:direct_2].to_f + params[:direct_3].to_f + params[:direct_4].to_f
    @total_direct = comm_5 + comm_6 + comm_7 + comm_8
    redirect_to standard_affiliate_earnings_path(:direct => @total_direct, :total_count => @total_count)
  end
  
  def standard_affiliate_calculator
    @total_direct = params[:direct] unless params[:direct].nil?
    @total_count = params[:total_count].to_f

    
  end
  
  def home
  end
  
  def tips
  end
  
  def help
  end
  
  def page
  end
  
  def breeasy_affiliate_program
    @affiliate = User.find params[:affiliate_id]
    
  end
end

app/helpers/affiliates_helper.rb
module AffiliatesHelper
  def affiliate_type(master)
    retval = "Standard"
    if master
      retval = "Master"
    end
    return retval
  end
  
  def product_interval(interval)
    retval = "Monthly"
    if interval == 2
      retval = "Annual"
    end
    return retval
  end
end

app/views/affiliates/_products.html.erb
<% if current_user.master %>
<h2>Master Affiliate Commission Schedule - Updated 01/25/2013</h2>
	<table>
		<thead><th>Id</th><th>App Plan</th><th>Interval</th><th>New Commission</th><th>Renewal Commission</th><th>Sub-Commission</th></thead>
		<tbody>
			<% Product.active.master.each do |p| %>
				<tr><td><%= p.id %></td><td><%= p.name %></td><td><%= product_interval(p.interval) %></td><td><%= number_to_percentage(p.new * 100, :precision => 0) %></td><td><%= number_to_percentage(p.renewal * 100, :precision => 0) %></td><td><%= number_to_percentage(p.sub_commission * 100, :precision => 0) %></td></tr>
			<% end %>
		</tbody>
	</table>
<% else %>
<h2>Standard Affiliate Commission Schedule - Updated 01/25/2013</h2>
	<table>
		<thead><th>Id</th><th>App Plan</th><th>Interval</th><th>New Commission</th><th>Renewal Commission</th></thead>
		<tbody>
			<% Product.active.standard.each do |p| %>
				<tr><td><%= p.id %></td><td><%= p.name %></td><td><%= product_interval(p.interval) %></td><td><%= number_to_percentage(p.new * 100, :precision => 0) %></td><td><%= number_to_percentage(p.renewal * 100, :precision => 0) %></td></tr>
			<% end %>
		</tbody>
	</table>
<% end %>

app/views/affiliates/_quote.html.erb
<blockquote>"The Breeasy Affiliate Programs, like all our products, are designed to be simple, easy to use, and create revenue opportunities for businesses that have cross promotional opportunities and related services.  I invite you to become an affiliate, try our apps and generate value-added profits from your blog, web content or complimentary service."<br>
- Tom 0., Founder, Breeasy.com
</blockquote>

app/views/affiliates/_signup_form.html.erb
<%= form_for @user, :url => {:controller => 'users', :action => 'create'} do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>An error occurred.</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
<% if master %>

	    <%= f.hidden_field :master, :value => master %>
		<%= f.hidden_field :account_executive_id, :value => 1 %>
	    
		
<% end %>
<% if master_id %>

	    <%= f.hidden_field :master_id, :value => master_id %>
		
<% end %>


  <p class="button"><%= f.submit "Create Affiliate" %></p>
<% end %>

app/views/affiliates/_standard_affiliate.html.erb
<h1>Earn commissions selling and referring Breeasy</h1>
<p>It's easy to <i>Earn</i> with Breeasy!  Our affiliate program is designed to add substantial revenue to your blog, newsletter, small business content, and online retail site.  All you got to do is signup, read and agree to the terms, get your referral code and embeddable html and you are on your way.</p>
<h2>Free! - Earn up to 35% on Paid Plans</h2>
<p>Earn 35% commissions on all new annual paid <a href="http://www.breeasy.com/plans">plans</a>.  You'll earn commissions on renewals, too - up to 25%.  These commission rates are subject to change and some limitations apply.  Current commission rates are published on your Affiliate Dashboard.
    <h2>How it Works</h2>
<p>Each affiliate creates their own unique referral code and is provided an embeddable html link that includes your referral code.  Once a user clicks your link, or enters your referral code when they sign up, that account is always linked to your affiliate code.  For example, if they start with a <a href="http://www.breeasy.com/apps/breeasy-for-business">Breeasy for Small Business Risk Free Trial</a>, then upgrade to a paid plan, you'll earn on each paid subscription. It never expires. </p>

<h2>On Demand Tracking and Reporting</h2>
<p>Do you like to manage your affiliate program in real time?  You can with the Breeasy Affiliate Program.  You can see how many trials, plans, and renewals are active and pending.</p>

app/views/affiliates/affiliate_calculator.html.erb
<div class="breadcrumbs"><a href="http://www.breeasy.com">Breeasy.com</a> > <a href="http://www.breeasy.com/opportunities">Opportunities</a> > <a href="http://affiliate.breeasy.com">Breeasy Affiliate Programs</a> > Master Affiliate Earnings Calculator</div>

<div id="bd">
	<div class="yui-g">
		<h1>Breeasy Master Affiliate Earnings Calculator</h1>
		<%= form_tag calculate_commissions_path, :id => "master_calculator_form", :method => :post do %>
		<h2>Step 1.  Number of Direct Subscriptions</h2>
		<p>Enter the number of subscriptions, by paid plan type, that you expect to signup or sell directly to your customers as a Master Affiliate in your first year. The numbers shown are for demonstration purposes only.</p>
		<table>
			<thead><tr><th>Id</th><th>Paid Plan</th><th>Interval</th><th>Price</th><th>Commission Rate</th><th>Number of Subscriptions Sold</th></tr></thead>
			<tbody>
				<% Product.active.master.each do |p| %>
					<tr><td><%= p.id %></td><td><%= p.name %></td><td><%= product_interval(p.interval) %></td><td><%= number_to_currency(p.price) %></td><td><%= number_to_percentage(p.new * 100, :precision => 0) %></td><td><%= text_field_tag "direct_#{p.id}", 20 %></td></tr>
				<% end %>
			</tbody>
		</table>
			<h2>Step 2.  Number of Sub-Affiliates</h2>
			<p>Enter the total number of sub-affiliates and sales reps you expect to signup as a Master Affiliate.  Again, the numbers shown are for demonstration purposes.</p>
			<table>
				<tbody>
					<tr><td>Number of Sub-Affiliates</td><td><%= text_field_tag :number_of_subs, 20 %></td></tr>
				</tbody>
			</table>
			<h2>Step 3.  Average Number of Subscriptions per Sub-Affiliate</h2>
			<p>Enter the average number of subscriptions per sub-affiliate/sales rep for each paid plan.  The average number shown are just examples, please put in your own numbers.</p>
				
			<table>
				<thead><tr><th>Id</th><th>Paid Plan</th><th>Interval</th><th>Price</th><th>Commission Rate</th><th>Average Plans Sold per Sub-Affiliate</th></tr></thead>
				<tbody>
					<% Product.active.master.each do |p| %>
						<tr><td><%= p.id %></td><td><%= p.name %></td><td><%= product_interval(p.interval) %></td><td><%= number_to_currency(p.price) %></td><td><%= number_to_percentage(p.sub_commission * 100, :precision => 0) %></td><td><%= text_field_tag "sub_#{p.id}", 20 %></td></tr>
					<% end %>
				</tbody>
			</table>
			<h2>Step 4.  Review Potential Earnings</h2>
			<table>
				<thead><tr><th># of Direct</th><th>Direct Earnings</th><th># of Subs</th><th>Sub-Affiliate Earnings</th><th>Total</th></tr></thead>
				<tbody>

						<tr><td><%= @total_count %></td><td><%= number_to_currency(@total_direct) %></td><td><%= @sub_count %></td><td><%= number_to_currency(@total_sub) %></td><td><%= number_to_currency(@total) %></td></tr>

				</tbody>
			</table>
			<p><%= submit_tag "Calculate Earnings", :name => nil %></p>
			<% end %>
			<p>Assumptions - Calculates estimated earnings per year.  Monthly subscriptions are assumed to last a full year regardless of start date.  All calculations are based on current plan prices, without any discounts or promotions.</p>		
			<p>Remember - These earnings are in the first year - You will continue to earn commissions on all renewals - up to  40% on paid renewals - and they're automatic!</p>
			<p><a href="http://affiliate.breeasy.com/master-affiliate-signup">I like it.  Tell me more</a>.</p>	
			
		
	</div>
</div>

app/views/affiliates/financials.html.erb
<div class="breadcrumbs"><a href="http://affiliate.breeasy.com">Breeasy Affiliate Programs</a> > <%= link_to "Dashboard", user_affiliates_path(current_user.id) %> > Financials</div>
<h1>Help</h1>
<div id="bd">
	<div class="yui-g">
		<h2>Recent Paid Subscriptions</h2>
		<table>
			<thead><th>App</th><th>Plan</th><th>Date</th><th>email</th></thead>
		</table>
		<h2>Earnings</h2>
		<table>
			<thead><th>This Week</th><th>This Month</th><th>This Year</th><th</thead>
		</table>
		
	</div>
</div>

app/views/affiliates/home.html.erb
<div class="breadcrumbs"><a href="http://www.breeasy.com">Breeasy.com</a> > <a href="http://www.breeasy.com/opportunities">Opportunities</a> > <a href="http://affiliate.breeasy.com">Breeasy Affiliate Programs</a></div>

<div id="bd">
	<div class="yui-ge"> 
	    <div class="yui-u first"> 
			<h1>Earn Big Money with our Super Easy Affiliate Programs</h1>
		</div> 
	    <div class="yui-u"> 
			<% unless current_user.nil? %>
				<p><%= link_to "Go to my Affiliate Dashboard", user_affiliates_path(current_user.id) %></p>				
			<% else %>
				<p>Already a Breeasy Affiliate Member?  <%= link_to "Login", login_path %></p>
			<% end %>		    
		</div> 
	</div>
	<div class="yui-g">
		
		<h2 class='section_header'>Make Breeasy <em>Your</em> Small Business with our Master Affiliate Program</h2><p>Looking for an interesting, simple, easy, and profitable small business of your own?  Need to maximize your income?  Looking for a part-time opportunity with unlimited upside potential? Know lots of people who are great at selling or know lots of freelancers, consultants, or small business owners? Becoming a <a href="http://affiliate.breeasy.com/master-affiliate-signup">Breeasy Master Affiliate</a> is just for you.  You can earn commissions of up to 50% on new paid subscriptions and up to 40% on paid renewals.  Plus, you can recruit you own sub-affiliates and sales representatives and earn from every subscription <em>they sell</em>.  Some conditions apply.</p>
	</div>
	<div class="yui-gb">
		<div class="yui-u first">
			<p><a href="http://affiliate.breeasy.com/master-affiliate-earnings-calculator">How Much Can I Earn as a Master Affiliate?</a></p>
		</div>
		<div class="yui-u">
			<p><a href="http://affiliate.breeasy.com/master-affiliate-signup">Tell me more about being a Master Affiliate</a></p>	
		</div>
		<div class="yui-u">
			<p><%= link_to "New! Mobile Affiliate Management", "http://affiliate.breeasy.com/mobile/index.html" %></p>
		</div>
	</div>
	<div class="yui-g">
		<h2 class='section_header'>Earn with Breeasy!  Free Standard Affiliate Program</h2><p> Want to make some extra money referring Breeasy to your customers or advertise Breeasy on your website or newsletter?  The Standard Affiliate Program could be your simple, easy solution.  You can earn commissions of up to 35% on new paid subscribers and up to 25% on all paid renewals.  Some conditions apply.</p>
	</div>
	<div class="yui-gb">
		<div class="yui-u first">
			<p><a href="http://affiliate.breeasy.com/standard-affiliate-earnings-calculator">How much can I earn as a Standard Affiliate?</a></p>
		</div>
		<div class="yui-u">
			<p><%= link_to "Start my Free Affiliate Membership", new_standard_path %></p>
		</div>
		<div class="yui-u">
			<p><%= link_to "Signup Customers Wherever you are!", "http://affiliate.breeasy.com/mobile/index.html" %></p>
			
		</div>
	</div>
	<div class="yui-g">
		<h2>Low Pressure Sales</h2>
		<p>No matter which affiliate program you choose, there are no high pressure sales gimmicks, crazy minimums, or pre-purchase of subscriptions that you must then sell.  At Breeasy, we believe in FREE, as in Free to try.  Some of our apps are completely free.  Our programs allow for your users to sign up for one of the apps, either free or trial, use your affiliate/referral code, and upgrade to one of our paid subscriptions when ready.  Your affiliate code stays with the user always and each affiliate member gets credit for all upgrades.</p>
	</div>	
	
	
	<div class="yui-g">
	    <div class="yui-u first">
		<h1>Standard Affiliate Program</h1>
		<ul class='features'>
			<li>Free!</li>
			<li>Earn up to 35% on paid plans</li>
			<li>Earn up to 25% on renewals</li>
			<li>On Demand Tracking</li>
			<li><%= link_to "Earnings Calculator", standard_affiliate_earnings_path %></li>
			<li>Signup and Earn Today!</li>
		</ul>
		<p><%= link_to "Standard Affiliate Program Details", new_standard_path %></p>
		</div>
	    <div class="yui-u">
	    <h1>Master Affiliate Program</h1>
		<ul class="features">
			<li>Make Breeasy <em>Your</em> Small Business!</li>
			<li>Earn up to 50% on all paid plans</li>
			<li>Earn up to 40% on renewals</li>
			<li>Easy admin and reporting</li>
			<li>Create a salesforce of affiliates and reps</li>
			<li><%= link_to "Earnings Calculator", master_affiliate_earnings_path %></li>
			<li>Exclusive offers</li>
			<li>Dedicated Account Executive to help you succeed</li>
			<li>Signup Now!</li>
		</ul>
		<p><%= link_to "Master Affiliate Program Details", new_master_path %></p>		
		
		</div>
	</div>

</div>

app/views/affiliates/new_standard.html.erb
<div class="breadcrumbs"><a href="http://www.breeasy.com">Breeasy.com</a> > <a href="http://www.breeasy.com/opportunities">Opportunities</a> > <a href="http://affiliate.breeasy.com">Breeasy Affiliate Programs</a> > Standard Affiliate Program</div>

<div id="bd">
	<div class="yui-g">
	    <div class="yui-u first">
		<h1>Sign Up Now!</h1>
		<%= render :partial => 'affiliates/signup_form', :locals => {:master => false, :master_id => nil} %>
			<%= link_to "Already have a Login?", login_path %>
			<blockquote>"The Breeasy Affiliate Program, like all our products, is designed to be simple, easy to use, and create revenue opportunities for businesses that have cross promotional opportunities and related services.  I invite you to become an affiliate, try our apps and generate value-added profits from your blog, web content or complimentary service."<br>
		- Tom 0., Founder, Breeasy.com

		</blockquote>
		 </div>
	    <div class="yui-u">
		<%= render :partial => 'affiliates/standard_affiliate' %>
		<h2>Want to earn even more Commissions?</h2>
		<p>Be sure and check out the Breeasy Master Affiliate Program.  <%= link_to "Earn up to 50% on paid subscriptions", new_master_path %>.</p>
		</div>
		

	</div>
</div>

app/views/affiliates/show.html.erb
<div class="breadcrumbs"><a href="http://www.breeasy.com">Breeasy.com</a> > <a href="http://www.breeasy.com/opportunities">Opportunities</a> > Affiliate Program</div>

<div id="bd">

		<div class="yui-g">
			<% if current_user %>
			<h1>Welcome to the Breeasy Affiliate Program, Your Name Here!</h1>
		    <div class="yui-u first">
			
			<h2>Your Details</h2>
			<table>
				<thead></thead>
				<tbody>
					<tr><td>Login:</td><td><%= current_user.email %></td></tr>
					<% unless current_user.affiliate_detail.nil? %>
						<tr><td>First Name:</td><td><%= current_user.affiliate_detail.first_name %></td></tr>
						<tr><td>Last Name:</td><td><%= current_user.affiliate_detail.last_name %></td></tr>
						<tr><td>Company:</td><td><%= current_user.affiliate_detail.company %></td></tr>
						<tr><td>Address:</td><td><%= current_user.affiliate_detail.address %></td></tr>
						<tr><td>City:</td><td><%= current_user.affiliate_detail.city %></td></tr>
						<tr><td>State:</td><td><%= current_user.affiliate_detail.state %></td></tr>
						<tr><td>Post Code:</td><td><%= current_user.affiliate_detail.post_code %></td></tr>
						<tr><td>Affiliate Code:</td><td><%= current_user.affiliate_detail.affiliate_code %></td></tr>
						<tr><td>Affiliate URL:</td><td><%= current_user.affiliate_detail.affiliate_url %></td></tr>
						<tr><td colspan="2"><%= link_to "Edit", edit_affiliate_path %></td></tr>
						
					<% else %>
						<tr><td colspan="2"><%= link_to "Enter your Details", new_affiliate_details_path %></td></tr>
					
					<% end %>
				</tbody>
			</table>
		    	
			 </div>
		    <div class="yui-u">
			<h2>Recent Activity</h2>
			</div>
			<% else %>
			<p>Signup or login</p>
			<% end %>
		</div>

</div>
	

app/views/affiliates/standard_affiliate_calculator.html.erb
<div class="breadcrumbs"><a href="http://www.breeasy.com">Breeasy.com</a> > <a href="http://www.breeasy.com/opportunities">Opportunities</a> > <a href="http://affiliate.breeasy.com">Breeasy Affiliate Programs</a> > Standard Affiliate Earnings Calculator</div>

<div id="bd">
	<div class="yui-g">
		<h1>Breeasy Standard Affiliate Earnings Calculator</h1>

		<%= form_tag standard_calculate_commissions_path :method => :post do %>
			<h2>Step 1.  Number of Subscriptions</h2>
			<p>Enter the number of subscriptions, by paid plan type, that you expect to signup or sell directly to your customers as a Breeasy Affiliate in your first year. The numbers shown are for demonstration purposes only. Please enter an appropriate number of subscriptions based on your business experience and customer base.</p>
		
		<table>
			<thead><tr><th>Id</th><th>Plan</th><th>Interval</th><th>Price</th><th>Commission Rate</th><th>Number of Subscriptions sold per year</th></tr></thead>
			<tbody>
				<% Product.active.standard.each do |p| %>
					<tr><td><%= p.id %></td><td><%= p.name %></td><td><%= product_interval(p.interval) %></td><td><%= number_to_currency(p.price) %></td><td><%= number_to_percentage(p.new * 100, :precision => 0) %></td><td><%= text_field_tag "direct_#{p.id}", 75 %></td></tr>
				<% end %>
			</tbody>
		</table>
	

		<h2>Step 2. Review Potential Earnings</h2>
		<table>
			<thead><tr><th># of Subs</th><th>Annual Total</th></tr></thead>
			<tbody>

					<tr><td><%= @total_count %></td><td><%= number_to_currency(@total_direct) %></td></tr>

			</tbody>
		</table>
		<p><%= submit_tag "Calculate Earnings", :name => nil%></p>
		<% end %>
		<p>Assumptions - Calculates estimated earnings per year.  Monthly subscriptions are assumed to last a full year regardless of start date.  All calculations are based on current plan prices, without any discounts or promotions.</p>		
		<p>Remember - These earnings are in the first year - You will continue to earn commissions on all renewals - up to  25% on paid renewals - and they're automatic!</p>
		<p><%= link_to "Start my Free Affiliate Membership", new_standard_path %></p>
		
	</div>
</div>

app/views/affiliates/sub_affiliate.html.erb
<div class="breadcrumbs"><a href="http://www.breeasy.com">Breeasy.com</a> > <a href="http://www.breeasy.com/opportunities">Opportunities</a> > <a href="http://affiliate.breeasy.com">Breeasy Affiliate Programs</a> > Sub-Affiliate Signup</div>

<div id="bd">
	<div class="yui-g">
	    <div class="yui-u first">
		<h1>Sub-Affiliate and Sales Rep Signup</h1>
		<h3>Partner/Master Affiliate Name:  <%= @master_affiliate.affiliate_detail.company %></h3>
		<p>Creating your sub-affiliate or Sales Representative account with your Breeasy Master Affiliate <%= @master_affiliate.affiliate_detail.company %> is free and easy.  Just complete the form below, 
			accept the terms on the next page and you will be earning commissions in no time.  More Details are over on the right.</p>
		<%= render :partial => 'affiliates/signup_form', :locals => {:master => false, :master_id => @master_affiliate.id} %>
			<%= link_to "Already have a Login?", login_path %>
			<%= render :partial => 'affiliates/quote' %>
		 </div>
	    <div class="yui-u">
	    <h1>Breeasy Sub-Affiliate Program</h1>
		
		<%= render :partial => 'affiliates/standard_affiliate' %>
		

		</div>
		

	</div>
</div>