config/routes.rb
BreeasyContact::Application.routes.draw do

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"

  resources :users do
    resources :affiliates
  end
  
  resources :sessions
  resources :contacts
  
  namespace :api do
      namespace :v1 do
        resources :users, :apps
      end
    end
 resources :breeasy_affiliates, :only => [:show, :new, :create, :edit, :update] 
  
  match 'thank_you/:id' => 'contacts#thank_you', :as => 'thank_you'
  match 'new_affiliate_details' => 'users#new_affiliate_details', :as => :new_affiliate_details
  match 'users/create_affiliate_details' => 'users#create_affiliate_details', :as => :create_affiliate_details
  match 'affiliate-home' => 'affiliates#home', :as => :affiliate_home
  match 'affiliate-tips' => 'affiliates#tips', :as => :affiliate_tips
  match 'affiliate-help' => 'affiliates#help', :as => :affiliate_help
  match 'affiliate-page' => 'affiliates#page', :as => :affiliate_page
  match 'affiliate-financials' => 'affiliates#financials', :as => :affiliate_financials
  match 'master-affiliate-signup' =>'affiliates#new_master', :as => :new_master
  match 'standard-affiliate-signup' => 'affiliates#new_standard', :as => :new_standard
  match 'master-affiliate-earnings-calculator' => 'affiliates#affiliate_calculator', :as => :master_affiliate_earnings
  match 'calculate-commissions' => 'affiliates#calculate_commissions', :as => :calculate_commissions
  match 'standard-affiliate-earnings-calculator' => 'affiliates#standard_affiliate_calculator', :as => :standard_affiliate_earnings
  match 'standard-calculate-commissions' => 'affiliates#standard_calculate_commissions', :as => :standard_calculate_commissions
  match 'sub-affiliate/:master_id' => 'affiliates#sub_affiliate', :as => :sub_affiliate
  match 'api/v1/user/login' => 'api/v1/users#login'
  match 'users/create_contact' => 'users#create_contact'
  match 'breeasy-affiliate-program/:affiliate_id' => "affiliates#breeasy_affiliate_program", :as => :breeasy_affiliate_program
  match 'breeasy-affiliate-sample-page' => "breeasy_affiliates#sample", :as => :breeasy_affiliate_page_sample
  match 'breeasy-affiliate-preview-page' => "breeasy_affiliates#preview", :as => :breeasy_affiliate_preview
  root :to => 'affiliates#home'
  
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Earn Big Money Free Affiliate Program | Breeasy.com</title>
	<%= stylesheet_link_tag "http://yui.yahooapis.com/combo?2.9.0/build/reset-fonts-grids/reset-fonts-grids.css&2.9.0/build/base/base-min.css" %>
	<%= stylesheet_link_tag 'application' %>
	<%= javascript_include_tag "application" %>
    

  <%= csrf_meta_tags %>
</head>
 <div id="doc2"class="yui-t7">
<div id="app_header">
    	<a href="http://www.breeasy.com"><img src="http://www.breeasy.com/images/communicate_manage_grow.png" alt="small business productivity platform" width="400" height="53" /></a>
    	 	<div id="promo_links">
    	 		<a href="http://billing.breeasy.com/users/sign_up">Invoice and Manage Cash - Free</a>
    		</div>
    	</div>
	    <div id='hd'>
		    <div id='navigation'>
				<ol id="navlinks">
					<li><a href="http://www.breeasy.com">Home</a></li>
					<li><a href="http://www.breeasy.com/apps/index.html">Apps</a></li>
					<li><a href="http://www.breeasy.com/plans/index.html">Plans and Pricing</a></li>
					<li><a href="http://www.breeasy.com/affiliate-program/index.html">Affiliate Program</a></li>
					<li><a href="http://brze.me">Blog</a></li>
					<li><a href="http://www.breeasy.com/articles/index.html">Articles</a></li>
					<li><a href="https://breeasy.desk.com">Support</a></li>
					<li><a href="http://www.breeasy.com/about.html">About</a></li>
					<li><a href="http://www.breeasy.com/opportunities/index.html">Opportunities</a></li>
					<li><a href="http://www.breeasy.com/apps/login-links.html">Login</a></li>
					<li class="last"></li>
					<li class="last"><a href="https://twitter.com/#!/EasyBreeasy"><img src="http://www.breeasy.com/images/twitter-24x24.jpg" alt="follow us on twitter" width="24" height="24" title="follow us on twitter" /></a></li>
<li class="last"><a href="http://www.facebook.com/breeasy"><img src="http://www.breeasy.com/images/facebook-24x24.png" alt="rss" width="24" height="24" title="Check out our Facebook page" /></a>
</li>
<li class="last"><a href="http://www.linkedin.com/company/breeasy-com"><img src="http://www.breeasy.com/images/linkedin-24x24.png" alt="rss" width="24" height="24" title="Breeasy on LinkedIn" /></a>
</li>
				</ol>
				
			</div>
		</div> <!-- hd -->


<body>
	<% flash.each do |name, msg| %>
	    <%= content_tag :div, msg, :id => "flash#{name}" %>
	  <% end %>
	
	<%= yield %>
</div>
<div id='ft' class="center">
	<p id='goodbye'>copyright &copy; 2012 - 2013 Breeasy.com</p>
</div>
</body>
</html>

app/views/layouts/breeasy_affiliates.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Breeasy Apps Available from <%= @affiliate.affiliate_detail.company %></title>
	<%= stylesheet_link_tag "http://yui.yahooapis.com/combo?2.9.0/build/reset-fonts-grids/reset-fonts-grids.css&2.9.0/build/base/base-min.css" %>
	<%= stylesheet_link_tag 'application' %>
	<%= javascript_include_tag "application" %>
    

  <%= csrf_meta_tags %>
</head>
<body>
	<div id="doc2"class="yui-t7">
	    <div id='hd'>

		</div> <!-- hd -->



	
		<%= yield %>
	</div>

<div id='ft' class="center">
	<p id='goodbye'>copyright &copy; 2012 - 2013 Breeasy.com</p>
</div>
</body>
</html>

app/views/layouts/members.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Earn Big Money Free Affiliate Program | Breeasy.com</title>
	<%= stylesheet_link_tag "http://yui.yahooapis.com/combo?2.9.0/build/reset-fonts-grids/reset-fonts-grids.css&2.9.0/build/base/base-min.css" %>
	<%= stylesheet_link_tag 'application' %>
	<%= javascript_include_tag "application" %>
    

  <%= csrf_meta_tags %>
</head>
 <div id="doc2"class="yui-t7">
<div id="app_header">
    	<a href="http://www.breeasy.com"><img src="http://www.breeasy.com/images/communicate_manage_grow.png" alt="small business productivity platform" width="400" height="53" /></a>
    	</div>
	    <div id='hd'>
		    <div id='navigation'>
				<ol id="navlinks">
					<li><%= link_to "Dashboard", user_affiliates_path(current_user.id) %></li>
					<li><%= link_to "Tips", affiliate_tips_path %></li>
					<li><%= link_to "Help", affiliate_help_path %></li>
					<li><%= link_to "Your Affiliate Page", affiliate_page_path %></li>
					<li><%= link_to "Financials" %></li>
					<li><%= link_to "Logout", logout_path %></li>
					
					
					

					
					
			</ol>
				
			</div>
		</div> <!-- hd -->


<body>
	<% flash.each do |name, msg| %>
	    <%= content_tag :div, msg, :id => "flash#{name}" %>
	  <% end %>
	
	<%= yield %>
</div>
<div id='ft' class="center">
	<p id='goodbye'>copyright &copy; 2012 - 2013 Breeasy.com</p>
</div>
</body>
</html>